[TH2-4954] th2 transport protocol support
th2-net/th2-read-log pull request #48
Opened 2023-07-04 13:51 UTC by lumber1000

2023-07-06 07:41 UTC, Nikita-Smirnov-Exactpro requested changes

2023-07-06 07:41 UTC, Nikita-Smirnov-Exactpro commented on README.md
> ++ Added support for th2 transport protocol
Could you please add information about new configuration option

2023-07-06 07:41 UTC, Nikita-Smirnov-Exactpro commented on README.md
> +**com.exactpro.th2.readlog.impl.ProtoRegexpContentParser**
Please add infromation about TransportRegexpContentParser

2023-09-29 07:48 UTC, Nikita-Smirnov-Exactpro approved these changes

2023-10-02 06:02 UTC, OptimumCode approved these changes

2023-11-21 06:48 UTC, merged